"""empty message

Revision ID: 190d860c841e
Revises: 1ab9c0e1524d
Create Date: 2023-10-11 15:14:15.125538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '190d860c841e'
down_revision = '1ab9c0e1524d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_payment_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_order_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_payment_list', schema=None) as batch_op:
        batch_op.drop_column('first_order_time')

    # ### end Alembic commands ###
