"""empty message

Revision ID: 35d3bffce5d2
Revises: 6fb6d1eb4529
Create Date: 2023-08-04 23:59:47.369378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35d3bffce5d2'
down_revision = '6fb6d1eb4529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menu_options', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('menu_options')

    # ### end Alembic commands ###
