"""empty message

Revision ID: 413c06ba945e
Revises: 79ad57213c28
Create Date: 2023-09-16 01:37:29.426230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413c06ba945e'
down_revision = '79ad57213c28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['tel'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
