"""empty message

Revision ID: 56ac131a4e27
Revises: 20ac56ed8149
Create Date: 2023-08-03 18:38:56.983785

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '56ac131a4e27'
down_revision = '20ac56ed8149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', mysql.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
