"""empty message

Revision ID: 56c9bd376845
Revises: 5afd36d26f4f
Create Date: 2023-05-10 16:17:39.895376

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '56c9bd376845'
down_revision = '5afd36d26f4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test2', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.Text(), nullable=True))
        batch_op.drop_column('test2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test2', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test2', mysql.TEXT(), nullable=True))
        batch_op.drop_column('test')

    # ### end Alembic commands ###
