"""empty message

Revision ID: 5afd36d26f4f
Revises: 979fc7506b5e
Create Date: 2023-05-05 23:07:25.899971

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5afd36d26f4f'
down_revision = '979fc7506b5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test2')
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test2', sa.Text(), nullable=True))
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', mysql.TEXT(), nullable=True))
        batch_op.drop_column('test2')

    op.create_table('test2',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('body', mysql.TEXT(), nullable=True),
    sa.Column('test', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
