"""empty message

Revision ID: 5d1366e3798b
Revises: 780361143864
Create Date: 2023-09-13 16:47:32.589932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d1366e3798b'
down_revision = '780361143864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.drop_column('tel')
        batch_op.drop_column('sub_description')
        batch_op.drop_column('manager_tel')
        batch_op.drop_column('store_image')
        batch_op.drop_column('address')
        batch_op.drop_column('main_description')
        batch_op.drop_column('manager_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager_name', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('main_description', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('address', mysql.VARCHAR(length=150), nullable=False))
        batch_op.add_column(sa.Column('store_image', mysql.VARCHAR(length=150), nullable=False))
        batch_op.add_column(sa.Column('manager_tel', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('sub_description', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('tel', mysql.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
