"""empty message

Revision ID: 6038b75d5d85
Revises: 
Create Date: 2023-06-12 02:26:35.231219

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6038b75d5d85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_category', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'store', ['store_id'], ['id'])

    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'store', ['store_id'], ['id'])
        batch_op.create_foreign_key(None, 'menu_has_category', ['menu_has_category_id'], ['id'])
        batch_op.create_foreign_key(None, 'menu_option', ['menu_option_id'], ['id'])

    with op.batch_alter_table('menu_has_category', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'sub_category', ['sub_category_id'], ['id'])
        batch_op.create_foreign_key(None, 'main_category', ['main_category_id'], ['id'])

    with op.batch_alter_table('menu_option', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'store', ['store_id'], ['id'])

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'menu', ['menu_id'], ['id'])
        batch_op.create_foreign_key(None, 'table', ['table_id'], ['id'])
        batch_op.create_foreign_key(None, 'order_status', ['order_status_id'], ['id'])

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'table_order_list', ['table_order_list_id'], ['id'])
        batch_op.create_foreign_key(None, 'payment_method', ['payment_method_id'], ['id'])
        batch_op.create_foreign_key(None, 'store', ['store_id'], ['id'])

    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('sub_category', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'main_category', ['main_category_id'], ['id'])

    with op.batch_alter_table('table', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'table_category', ['table_category_id'], ['id'])

    with op.batch_alter_table('table_category', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'store', ['store_id'], ['id'])

    with op.batch_alter_table('table_order_list', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'order', ['ordered_id'], ['id'])
        batch_op.create_foreign_key(None, 'order_status', ['order_status_id'], ['id'])
        batch_op.create_foreign_key(None, 'table', ['table_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthday', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('tel', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_logged_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=512),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.drop_index('username')
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('username', ['username'], unique=False)
        batch_op.alter_column('password',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=False)
        batch_op.drop_column('last_logged_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('address')
        batch_op.drop_column('tel')
        batch_op.drop_column('birthday')

    with op.batch_alter_table('table_order_list', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('table_category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('sub_category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('menu_option', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('menu_has_category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('main_category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
