"""empty message

Revision ID: 6d22b3139f0d
Revises: 190d860c841e
Create Date: 2023-10-11 16:28:52.542966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d22b3139f0d'
down_revision = '190d860c841e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_payment_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_payment_list', schema=None) as batch_op:
        batch_op.drop_column('discount')

    # ### end Alembic commands ###
