"""empty message

Revision ID: 743ed375c49f
Revises: 
Create Date: 2023-08-03 01:25:20.514185

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '743ed375c49f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('page', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=True))
        batch_op.drop_index('FK_table_table_category_page')
        batch_op.create_foreign_key(None, 'table_category', ['table_category_id'], ['id'])
        batch_op.drop_column('category_page_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_page_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('FK_table_table_category_page', ['category_page_id'], unique=False)
        batch_op.drop_column('position')
        batch_op.drop_column('page')
        batch_op.drop_column('table_category_id')

    # ### end Alembic commands ###
