"""empty message

Revision ID: 780361143864
Revises: 586f6b3d2f35
Create Date: 2023-09-13 01:02:44.004149

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '780361143864'
down_revision = '586f6b3d2f35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('store_pw', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint(None, ['store_id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_index('name')
        batch_op.drop_column('address')
        batch_op.drop_column('name')
        batch_op.drop_column('birthday')
        batch_op.drop_column('user_id')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('user_id', mysql.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('birthday', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('address', mysql.VARCHAR(length=150), nullable=False))
        batch_op.create_index('name', ['name'], unique=False)
        batch_op.create_index('email', ['email'], unique=False)

    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('store_pw')
        batch_op.drop_column('store_id')

    # ### end Alembic commands ###
