"""empty message

Revision ID: 7acb111015b8
Revises: 66274e22020e
Create Date: 2023-08-05 12:12:48.413717

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7acb111015b8'
down_revision = '66274e22020e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_category', schema=None) as batch_op:
        batch_op.drop_column('page')

    with op.batch_alter_table('table_category', schema=None) as batch_op:
        batch_op.drop_column('page')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page', mysql.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('main_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page', mysql.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
