"""empty message

Revision ID: 97c3746a1d37
Revises: 6d22b3139f0d
Create Date: 2023-10-11 18:09:20.362561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97c3746a1d37'
down_revision = '6d22b3139f0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_payment_list', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['store_id', 'table_id', 'first_order_time'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_payment_list', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
