"""empty message

Revision ID: c613199f7703
Revises: dcd6e66278d4
Create Date: 2023-10-18 14:49:45.351591

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c613199f7703'
down_revision = 'dcd6e66278d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_payment_list', schema=None) as batch_op:
        batch_op.drop_index('store_id')
        batch_op.create_unique_constraint(None, ['store_id', 'table_id', 'first_order_time'])
        batch_op.drop_constraint('table_payment_list_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'table', ['table_id'], ['id'])
        batch_op.create_foreign_key(None, 'store', ['store_id'], ['id'])
        batch_op.drop_column('table_order_list_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_payment_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_order_list_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('table_payment_list_ibfk_1', 'table_order_list', ['table_order_list_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('store_id', ['store_id', 'table_id', 'table_order_list_id'], unique=False)

    # ### end Alembic commands ###
