"""empty message

Revision ID: dcd6e66278d4
Revises: 97c3746a1d37
Create Date: 2023-10-17 01:56:43.887715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcd6e66278d4'
down_revision = '97c3746a1d37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_payment_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_order_list_id', sa.Integer(), nullable=True))
        batch_op.drop_index('store_id')
        batch_op.create_unique_constraint(None, ['store_id', 'table_id', 'table_order_list_id'])
        batch_op.create_foreign_key(None, 'table_order_list', ['table_order_list_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_payment_list', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('store_id', ['store_id', 'table_id', 'first_order_time'], unique=False)
        batch_op.drop_column('table_order_list_id')

    # ### end Alembic commands ###
